#+ description: Extended description of my query/operation.
#+     This can be a more extensive than the summary and in can span
#+     multiple lines.
#+
#+     Descriptions support (to some extent) [CommonMark](https://commonmark.org/help/).

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?band ?album ?genre WHERE {
  ?band rdf:type dbo:Band .
  ?album rdf:type schema:MusicAlbum .
  ?band dbo:genre ?genre .
  ?album dbp:artist ?band .
} LIMIT 100
